# Generated by Django 5.2.4 on 2025-07-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bootcamp_lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
